# Generated by Django 5.1 for Smart Task and Resource Allocation System

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software Engineering'), ('DESIGN', 'UI/UX Design'), ('DEVOPS', 'DevOps & Infrastructure'), ('QA', 'Quality Assurance & Testing'), ('DATA', 'Data & AI'), ('MANAGEMENT', 'Project Management')], default='SOFTWARE', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the skill competency')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FULL_STACK', 'Full Stack Developer'), ('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DEVOPS', 'DevOps Engineer'), ('QA_ENGINEER', 'QA Automation Engineer'), ('UI_UX', 'UI/UX Designer'), ('DATA_ENGINEER', 'Data Engineer'), ('LEAD', 'Technical Team Lead')], default='FULL_STACK', max_length=30)),
                ('max_capacity', models.PositiveIntegerField(default=3, help_text='Maximum number of concurrent active tasks this user can handle')),
                ('is_available', models.BooleanField(default=True, help_text='Designates whether this resource is currently available to take on new tasks')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='allocator.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent / Critical')], default='MEDIUM', max_length=10)),
                ('deadline', models.DateField(help_text='Target completion date')),
                ('estimated_hours', models.PositiveIntegerField(default=4, help_text='Estimated effort required in person-hours')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Allocation'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assigned resource (leave blank for automated allocation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('required_skill', models.ForeignKey(help_text='Primary technical competency required to execute this task', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='allocator.skill')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['deadline', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(default=0.0, help_text='Calculated compatibility score (0 - 100)')),
                ('reason', models.TextField(help_text='Explainable breakdown of factors leading to this assignment')),
                ('allocation_type', models.CharField(choices=[('AUTOMATIC', 'Smart Algorithm Allocation'), ('MANUAL', 'Manual Override / Direct Assignment')], default='AUTOMATIC', max_length=15)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_logs', to='allocator.task')),
            ],
            options={
                'verbose_name': 'Allocation Log',
                'verbose_name_plural': 'Allocation Logs',
                'ordering': ['-allocated_at'],
            },
        ),
    ]
